import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import localFont from 'next/font/local'
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const myFont = localFont({
//   src: '../utiles/fonts/Pretendard-Regular.otf',
//   display: 'swap'
// })

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        {/* <link 
          href="/src/utiles/fonts/Pretendard-Regular.otf" 
          rel="stylesheet"
        /> */}
      <body
        // className={inter.className}
        // className={myFont.className}
        >{children}
      </body>
    </html>
  );
}
