import type { Metadata } from "next";
import "./globals.css";
import * as fonts from "@/utiles/fonts/fonts";
import Header from "@/components/home/Header/Header";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontVariables  = Object.values(fonts).map(font => font.variable).join(' ');

  return (
    <html lang="en" className={`${fontVariables}`}>
      <body>
        <main>
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
